#配置datasource数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.43.221:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    password: www.mysql.com
    username: root

#配置mybatis
mybatis:
  mapper-locations: classpath:com/example/springbootmybatis/wang/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.example.springbootmybatis.wang.resposity